### ISSUE TITLE
Terminal commands

### ISSUE THREAD

**Issue by Hardhik2210030033** [mohammad-taheri1/Book-Store-MERN-Stack#2]
npm run dev command is not working, please help in this issue

**Comment by Hardhik2210030033** [comment]
![Uploading Screenshot 2024-04-22 104922.png…]()

**Comment by MomoTaheri** [comment]
what is the error ?

**Comment by MomoTaheri** [comment]
The picture is not loading. But the only reason can be your path. Make sure Your are in the right path for front-end project.
